[project]
name = "mlsmpm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kiinami", email = "kinami@posteo.net" }
]
requires-python = ">=3.14"
dependencies = [
    "nvtx>=0.2.16",
    "warp-sdk>=0.1.1",
    "core"
]

[tool.uv.sources]
core = { workspace = true }

[project.scripts]
mlsmpm = "mlsmpm:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
