[project]
name = "mpm16"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kiinami", email = "kinami@posteo.net" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
mpm16 = "mpm16:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
